# ansible-playbook -i inventory.ini 10-data-types.yaml

- name: data types
  hosts: local    # run playbook on the ansible server
  connection: local   # not ask for creds while running on the ansible server
  vars:
    course: "DevOps with AWS" # string
    duration: 120 #number
    topics: # list
    - linux
    - shell
    - ansible
    - terraform
    - jenkins
    - k8s
    live: true  # boolean
    tools:  # map/dictionary --> key-value pairs
      ci: jenkins # string
      cm: ansible
      cloud: aws
      aws:  # list
      - ec2
      - IAM
      - r53
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hello all, I'm learning {{ course }} which would be for {{ duration }} hrs. live sessions: {{live}}; topics covered: {{topics}}; tools used: {{tools}}"
    