- name: create ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-092ec119790ba2094"
    sg_id: "sg-0a1fb132f1fc1e49d"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - backend2
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: t3.micro
      security_group: "{{sg_id}}"
      network:
        assign_public_ip: true
      image_id: "{{ami_id}}"
    loop: "{{instances}}"
    register: ec2_instances

  - name: print ec2_instances
    ansible.builtin.debug:
      msg: "{{ec2_instances}}"
    
    