- name: create ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-092ec119790ba2094"
    sg_id: "sg-0a1fb132f1fc1e49d"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - backend2
    - frontend
    zone: "sprojex.in"
  tasks:
  - name: install boto3 and botocore for python
    ansible.builtin.command: pip3.9 install {{item}}
    loop:
    - boto3
    - botocore
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: t3.micro
      security_group: "{{sg_id}}"
      network:
        assign_public_ip: true
      image_id: "{{ami_id}}"
    loop: "{{instances}}"
    register: ec2_instances

  - name: print ec2_instances
    ansible.builtin.debug:
      msg: "{{ec2_instances}}"

  - name: create r53 records for private IPs
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 10
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}"

  - name: create r53 records for public IP of frontend
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{zone}}"
      type: A
      ttl: 10
      value: "{{item.instances[0].public_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}"
    when: item.item == "frontend"
    
    